/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BacnetMonitorRouteImport } from './routes/bacnet-monitor'
import { Route as ConfigurationRouteImport } from './routes/configuration'
import { Route as KnxMonitorRouteImport } from './routes/knx-monitor'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BacnetMonitorRoute = BacnetMonitorRouteImport.update({
  id: '/bacnet-monitor',
  path: '/bacnet-monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurationRoute = ConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => rootRouteImport,
} as any)
const KnxMonitorRoute = KnxMonitorRouteImport.update({
  id: '/knx-monitor',
  path: '/knx-monitor',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bacnet-monitor': typeof BacnetMonitorRoute
  '/configuration': typeof ConfigurationRoute
  '/knx-monitor': typeof KnxMonitorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bacnet-monitor': typeof BacnetMonitorRoute
  '/configuration': typeof ConfigurationRoute
  '/knx-monitor': typeof KnxMonitorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bacnet-monitor': typeof BacnetMonitorRoute
  '/configuration': typeof ConfigurationRoute
  '/knx-monitor': typeof KnxMonitorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bacnet-monitor' | '/configuration' | '/knx-monitor'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bacnet-monitor' | '/configuration' | '/knx-monitor'
  id: '__root__' | '/' | '/bacnet-monitor' | '/configuration' | '/knx-monitor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BacnetMonitorRoute: typeof BacnetMonitorRoute
  ConfigurationRoute: typeof ConfigurationRoute
  KnxMonitorRoute: typeof KnxMonitorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bacnet-monitor': {
      id: '/bacnet-monitor'
      path: '/bacnet-monitor'
      fullPath: '/bacnet-monitor'
      preLoaderRoute: typeof BacnetMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuration': {
      id: '/configuration'
      path: '/configuration'
      fullPath: '/configuration'
      preLoaderRoute: typeof ConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knx-monitor': {
      id: '/knx-monitor'
      path: '/knx-monitor'
      fullPath: '/knx-monitor'
      preLoaderRoute: typeof KnxMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BacnetMonitorRoute: BacnetMonitorRoute,
  ConfigurationRoute: ConfigurationRoute,
  KnxMonitorRoute: KnxMonitorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
